#!name = 云顶节点
#!desc = 记得在云顶插件内添加剩余配置

[General]
ipv6 = false
skip-proxy = localhost, *.local, captive.apple.com, e.crashlytics.com, 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16
bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.168.0.0/16, 224.0.0.0/4, 255.255.255.255/32
dns-server = 223.5.5.5, 119.29.29.29
doh-server = https://dns.alidns.com/dns-query
allow-udp-proxy = false
proxy-test-url = http://www.gstatic.com/generate_204
test-timeout = 3


[Proxy]


[Remote Proxy]


[Proxy Group]
PROXY = select, DIRECT


[Remote Filter]


[Rule]
IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
IP-CIDR,100.64.0.0/10,DIRECT,no-resolve


FINAL,DIRECT


[Remote Rule]
https://jihulab.com/jiuxiao1234/testpron/-/raw/master/rules.list, policy=DIRECT, tag=宝可梦拉码-业务直连, enabled=true


[Host]


[Rewrite]


[Script]


[Plugin]


[MITM]
hostname =
skip-server-cert-verify = false
enable = false
ca-passphrase =
ca-p12 =
